import type { Metadata } from "next";
import { absoluteSiteUrl } from "../../lib/site";
import { PolicyPage } from "../legal-shell";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Learn what Discord data Selenite accesses, stores, retains, shares, and deletes—and which controls are available to server administrators and users.",
  alternates: { canonical: absoluteSiteUrl("privacy/") },
  openGraph: { title: "Privacy Policy — Selenite", url: absoluteSiteUrl("privacy/") },
  robots: { index: true, follow: true },
};

const sections = [
  { id:"scope", title:"Scope and controller", content:<><p>This Privacy Policy explains how the independent developer operating Selenite (“we,” “us,” or the “operator”) processes information when Selenite is installed in a Discord server or used through Discord.</p><p>Discord separately processes information under its own privacy policy. Server owners and administrators may also be responsible for how they configure logging and moderation in their communities.</p></> },
  { id:"access", title:"Data Selenite accesses", content:<><p>Depending on the permissions, enabled features, and Discord events involved, Selenite may access:</p><ul><li>Discord user IDs, usernames, display names, avatars, banners, nicknames, roles, and membership state.</li><li>Server IDs, names, descriptions, owner details, member counts, settings, roles, channels, threads, invites, expressions, webhooks, and audit-log events.</li><li>Message metadata, reactions, attachments, and message content where Discord supplies it and a feature requires it.</li><li>Voice, presence, scheduled-event, AutoMod, and integration event metadata when relevant features are enabled.</li><li>Command inputs, button and menu selections, ModMail messages, and problem reports that users intentionally submit.</li></ul><p>Access does not mean every item is stored. Much of this information is processed transiently to answer a command or react to an event.</p></> },
  { id:"stored", title:"Data Selenite stores", content:<><p>Selenite stores only data needed for configured features. This can include:</p><ul><li>Server configuration and identifiers, including welcome designs, logging routes, role mappings, security settings, feature preferences, and the identity of administrators who changed them.</li><li>Moderation cases, including user and moderator IDs, action, reason, status, duration, and timestamps.</li><li>Bounded admin-log event records, including event type, involved user IDs, relevant channel or message IDs, reasons, summaries, and event details.</li><li>For configured message edit and deletion logging, the before, after, or deleted content and attachment references Discord made available from cache.</li><li>ModMail session metadata such as user, server, channel, assigned moderator, status, closure reason, and timestamps.</li><li>Reaction-role panel definitions, role IDs, message IDs, emoji mappings, and creator or updater IDs. Member reaction-role assignment history is not stored.</li><li>Optional SHARKMINT wallet records: user ID, balance, account tier, aggregate transaction totals, status, and timestamps.</li><li>A temporary structural backup while Raid Mode is active, containing server, channel, role, permission-overwrite, and webhook definitions. It does not contain a member snapshot.</li></ul></> },
  { id:"messages", title:"Message content and ModMail", content:<><p>Selenite does not create a general archive or snapshot of ordinary chat messages. If server administrators enable message edit or deletion logs, content may be captured only when that specific event occurs and Discord provides the content from cache. Administrators can exclude channels from message logging.</p><p>ModMail content is relayed between a user’s direct messages and a private server channel. If a server enables transcripts, up to the latest 100 messages can be assembled into a text file and delivered through Discord to the ModMail channel and the participating user. The transcript is not separately stored in Selenite’s database, but Discord may retain the delivered file and messages under its own systems and the server’s practices.</p></> },
  { id:"use", title:"How data is used", content:<><p>Data is used to provide requested commands and configured features; deliver moderation, logging, security, role, welcome, ModMail, and economy functions; maintain settings across restarts; diagnose failures and abuse; protect the Service and Discord communities; respond to reports and privacy requests; and comply with legal or Discord requirements.</p><p>Selenite does not sell or rent Discord API data, use it for third-party advertising, build marketing profiles, or use it to decide eligibility for employment, housing, credit, insurance, healthcare, or similar benefits.</p></> },
  { id:"legal-bases", title:"Legal bases", content:<><p>Where data-protection law requires a legal basis, processing is based as applicable on providing the Service requested by users and server administrators; legitimate interests in operating, securing, and improving Selenite and helping administrators protect their communities; consent or administrator choice for optional features; and compliance with legal obligations.</p><p>Administrators should enable optional logging only when they have an appropriate basis and have provided any notice required for their community.</p></> },
  { id:"sharing", title:"Who receives data", content:<><ul><li><strong>Discord:</strong> commands, bot responses, log messages, ModMail, transcripts, and other feature output are processed and delivered through Discord.</li><li><strong>Authorized server staff:</strong> administrators and moderators may receive configured logs, moderation records, reports, or ModMail content inside channels they control.</li><li><strong>Infrastructure providers:</strong> MongoDB Atlas processes stored bot data as a database service provider. Website and server hosting providers may process technical request data needed to deliver the services.</li><li><strong>The developer:</strong> problem reports are sent privately to the developer and include the reporter’s Discord identity and submission context for follow-up.</li><li><strong>Legal and safety recipients:</strong> information may be disclosed when required by law or reasonably necessary to protect users, rights, safety, Discord, or the Service.</li></ul><p>Discord API data is not shared with data brokers or advertising networks.</p></> },
  { id:"retention", title:"Retention and deletion", content:<><p>Database admin-log events use a default 30-day retention period configurable by server administrators from 1 to 90 days. They are also capped at 5,000 records or approximately 10 MiB per server, with global safety limits; the oldest records are removed first. Discord messages sent to log channels are separate and remain according to Discord and server administration.</p><p>Raid Mode keeps one structural backup only while needed for active protection and restoration. Wallet records remain until the user deletes the wallet. Other configuration, moderation cases, ModMail metadata, and panel mappings remain while needed to provide or document the configured feature, until removed through available controls, or until a verified deletion request is completed, subject to legal and security needs.</p><p>Problem reports are delivered as Discord direct messages rather than saved in Selenite’s database and remain until deleted from Discord by the recipient. Backup copies and provider-level deletion may take additional time to cycle out.</p></> },
  { id:"controls", title:"Your controls and rights", content:<><p>Server administrators can disable features, exclude channels from message logging, change retention, clear stored audit events, or delete managed Admin Logs through Selenite’s controls. Wallet users can permanently delete their wallet from <code>/wallet</code>.</p><p>To request access, correction, deletion, restriction, portability, or objection where applicable, run <code>/report-problem</code> and begin the summary with <strong>PRIVACY REQUEST</strong>. Include the relevant user ID and server ID. Requests are verified through Discord before data is disclosed or deleted. We aim to respond within 30 days or the period required by applicable law.</p><p>You may also have the right to complain to your local data-protection authority. Some records may be retained when legally required or necessary to establish, exercise, or defend legal claims.</p></> },
  { id:"automation", title:"Automated actions", content:<><p>Selenite can automatically assign roles, enforce administrator-created pre-ban lists, block newly added bots, expire temporary moderation actions, and react to Raid Mode events. These actions are triggered by explicit server configuration and Discord events, not behavioral profiling or machine learning.</p><p>Questions or disputes about a server’s moderation decision should first be directed to that server’s administrators. Privacy requests about Selenite’s stored data can be made through the process above.</p></> },
  { id:"security-transfers", title:"Security and international processing", content:<><p>Reasonable technical and organizational safeguards are used, including scoped Discord permissions, restricted developer access, bounded storage, and access-controlled infrastructure. No system can guarantee absolute security.</p><p>Discord, database, and hosting providers may process data in countries other than your own. Where required, those providers and the operator rely on legally recognized safeguards for international transfers.</p></> },
  { id:"children", title:"Age requirements", content:<><p>Selenite is intended only for people permitted to use Discord. It is not directed to children below Discord’s minimum age for their country, and users must follow Discord’s age requirements.</p></> },
  { id:"website", title:"This legal website", content:<><p>This site does not provide accounts, advertising, or optional analytics and does not intentionally set tracking cookies. Its hosting infrastructure may temporarily process standard technical information such as IP address, browser details, requested page, and timestamp to deliver and secure the site.</p></> },
  { id:"updates-contact", title:"Updates and contact", content:<><p>This policy may be updated as Selenite’s features, providers, or legal obligations change. The effective date will be revised when changes are published.</p><p>For privacy questions or requests, use <code>/report-problem</code> in Discord and mark the submission as a <strong>PRIVACY REQUEST</strong>. It is delivered privately to Selenite’s developer.</p></> },
];

export default function PrivacyPage() { return <PolicyPage eyebrow="Data practices" title="Privacy Policy" summary="A feature-by-feature explanation of what Selenite sees, what it keeps, and the controls available to you." effective="22 August 2026" sections={sections} />; }
