import type { Metadata } from "next";
import { absoluteSiteUrl } from "../../lib/site";
import { PolicyPage } from "../legal-shell";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Read the Terms of Use governing Selenite, a configurable Discord moderation and community-management bot.",
  alternates: { canonical: absoluteSiteUrl("terms/") },
  openGraph: { title: "Terms of Use — Selenite", url: absoluteSiteUrl("terms/") },
  robots: { index: true, follow: true },
};

const sections = [
  { id:"acceptance", title:"Acceptance of these terms", content:<><p>These Terms of Use (“Terms”) govern access to and use of Selenite, a Discord bot and related services (“Selenite” or the “Service”). By inviting Selenite, configuring it, running its commands, or interacting with its features, you agree to these Terms.</p><p>If you add or configure Selenite for a Discord server, you confirm that you are authorized by that server to do so. If you do not agree, do not use the Service and remove it from servers you control.</p></> },
  { id:"eligibility", title:"Eligibility and Discord rules", content:<><p>You must be permitted to use Discord under Discord’s Terms of Service and meet the minimum age required for Discord in your country. Your use of Selenite must also comply with Discord’s Terms, Community Guidelines, Developer policies as applicable, and all applicable laws.</p><p>Selenite is not designed to make Discord available to anyone who is not eligible to use Discord.</p></> },
  { id:"service", title:"What Selenite provides", content:<><p>Selenite provides configurable tools including moderation, administrative logging, welcome messages, role management, reaction roles, ModMail, security controls, server information, games, and optional economy features.</p><p>Features depend on Discord availability, the permissions granted to Selenite, server configuration, and technical capacity. Some features may be experimental, changed, suspended, or removed.</p></> },
  { id:"administrators", title:"Server administrators and configuration", content:<><p>Server owners and administrators control which optional features are enabled, which events are logged, where bot output is delivered, and which members may use administrative commands. They are responsible for configuring Selenite lawfully and informing their communities when local rules or laws require notice.</p><p>Actions requested through authorized commands—including role changes, moderation actions, channel operations, welcome messages, logging, pre-bans, and Raid Mode—may alter a server immediately. Selenite uses permission checks and confirmations where appropriate, but administrators remain responsible for their choices.</p></> },
  { id:"acceptable-use", title:"Acceptable use", content:<><p>You may not use Selenite to violate law or Discord policy; harass, exploit, deceive, or harm others; collect credentials or sensitive information; evade Discord safety systems; gain unauthorized access; distribute malware; spam; or overload, probe, reverse engineer, or disrupt the Service.</p><p>You may not represent Selenite as an official Discord product or use it to make automated decisions in prohibited high-impact areas such as employment, housing, insurance, credit, or healthcare.</p></> },
  { id:"automation", title:"Automated actions and moderation records", content:<><p>Selenite can carry out administrator-configured automation, such as role assignment, pre-ban enforcement, bot blocking, temporary moderation expiry, and emergency Raid Mode protections. These actions follow server settings and Discord events; they are not based on advertising profiles or machine-learning judgments.</p><p>Moderation logs and reports are operational aids, not guaranteed complete or authoritative records. Discord may not provide uncached content, audit-log attribution may be delayed, and users should review important actions before relying on them.</p></> },
  { id:"availability", title:"Availability and changes", content:<><p>The Service is provided on an “as available” basis. No uninterrupted uptime, error-free operation, permanent feature set, or preservation of data is promised. Maintenance, Discord API changes, rate limits, outages, permission changes, or third-party failures may affect functionality.</p><p>We may update Selenite and these Terms to reflect operational, security, legal, or product changes. Material changes will be identified by a new effective date on this page.</p></> },
  { id:"termination", title:"Suspension and termination", content:<><p>You may stop using Selenite at any time by removing it from your server and discontinuing interactions. Access may be limited or terminated when needed to protect users, Discord, Selenite, or others; to address abuse or security risk; to comply with law or Discord requirements; or when these Terms are violated.</p><p>Removing the bot does not itself delete messages previously delivered into Discord channels. Data deletion is handled as described in the Privacy Policy.</p></> },
  { id:"disclaimers", title:"Disclaimers and liability", content:<><p>To the fullest extent permitted by law, Selenite is provided without warranties, express or implied, including warranties of merchantability, fitness for a particular purpose, accuracy, non-infringement, or availability.</p><p>To the fullest extent permitted by law, the operator will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for loss of data, revenue, reputation, or server access arising from use of or inability to use Selenite. Nothing in these Terms excludes liability that cannot legally be excluded.</p></> },
  { id:"contact", title:"Questions and contact", content:<><p>For service or legal questions, use <code>/report-problem</code> in Discord and clearly identify the request as a legal or Terms inquiry. The report is delivered privately to Selenite’s developer.</p><p>Selenite is an independent application and is not affiliated with, sponsored by, or endorsed by Discord Inc.</p></> },
];

export default function TermsPage() { return <PolicyPage eyebrow="Usage agreement" title="Terms of Use" summary="The practical rules that keep Selenite useful, safe, and accountable inside Discord." effective="22 August 2026" sections={sections} />; }
